### ISSUE TITLE
AttributeError: 'UnImplemented' object has no attribute 'read'

### ISSUE THREAD

**Issue by niyonx** [yohanchatelain/pytracer#17]
This bug does not crash the visualize command but shows up when hovering over points of the timeline. (Threaded=True)

```bash
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functionsrule.endpoint
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1076, in dispatch
response.set_data(func(*args, outputs_list=outputs_list))
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1007, in add_context
output_value = func(*args, **kwargs)  # %% callback invoked %%
File "/project/6003600/niyonx/pytracer/pytracer/gui/callbacks.py", line 150, in print_heatmap
_ndarray = extra_value.read()
AttributeError: 'UnImplemented' object has no attribute 'read'
```

**Comment by yohanchatelain** [comment]
Resolved in Pytracer 2.0: clean-slate instrumentation architecture without legacy wrapper state.
