### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

### ISSUE THREAD

**Issue by niyonx** [yohanchatelain/pytracer#18]
Crash when hovering over timeline points in test_classifier_comparison.py. Visualize command when Threaded = True. It could be a multithreading error along with the segmentation fault error.

```bash
172.19.128.2 - - [10/Jun/2021 12:59:47] "POST /_dash-update-component HTTP/1.1" 200 -
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
172.19.128.2 - - [10/Jun/2021 12:59:47] "POST /_dash-update-component HTTP/1.1" 200 -
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
Exception ignored in: 'tables.utilsextension.e_walk_cb'
Exception ignored in: 'tables.utilsextension.e_walk_cb'
Traceback (most recent call last):
Traceback (most recent call last):
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/exceptions.py", line 118, in **init**
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/exceptions.py", line 118, in **init**
172.19.128.2 - - [10/Jun/2021 12:59:47] "POST /_dash-update-component HTTP/1.1" 200 -
self.h5backtrace = self._dump_h5_backtrace()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
self.h5backtrace = self._dump_h5_backtrace()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](https://www.notion.so/**req.view_args)
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1076, in dispatch
response.set_data(func(*args, outputs_list=outputs_list))
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1007, in add_context
output_value = func(*args, **kwargs)  # %% callback invoked %%
File "/project/6003600/niyonx/pytracer/pytracer/gui/callbacks.py", line 150, in print_heatmap
_ndarray = extra_value.read()
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/array.py", line 900, in read
arr = self._read(start, stop, step, out)
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/array.py", line 857, in _read
self._read_array(start, stop, step, arr)
File "tables/hdf5extension.pyx", line 1535, in tables.hdf5extension.Array._read_array
tables.exceptions.HDF5ExtError: HDF5 error back trace

File "H5Dio.c", line 199, in H5Dread
can't read data
File "H5Dio.c", line 592, in H5D__read
can't initialize I/O info
File "H5Dchunk.c", line 1228, in H5D__chunk_io_init
unable to create file chunk selections
File "H5Dchunk.c", line 1721, in H5D__create_chunk_file_map_hyper
can't insert chunk into skip list
File "H5SL.c", line 1122, in H5SL_insert
can't create new skip list node
File "H5Dio.c", line 199, in H5Dread
can't read data
File "H5SL.c", line 791, in H5D__read
can't insert duplicate key

End of HDF5 error back trace

Problems reading the array data.
172.19.128.2 - - [10/Jun/2021 12:59:48] "POST /_dash-update-component HTTP/1.1" 500 -
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](https://www.notion.so/**req.view_args)
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1076, in dispatch
response.set_data(func(*args, outputs_list=outputs_list))
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1007, in add_context
output_value = func(*args, **kwargs)  # %% callback invoked %%
File "/project/6003600/niyonx/pytracer/pytracer/gui/callbacks.py", line 150, in print_heatmap
_ndarray = extra_value.read()
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/array.py", line 900, in read
arr = self._read(start, stop, step, out)
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/array.py", line 857, in _read
self._read_array(start, stop, step, arr)
File "tables/hdf5extension.pyx", line 1535, in tables.hdf5extension.Array._read_array
tables.exceptions.HDF5ExtError: HDF5 error back trace

File "H5Dio.c", line 199, in H5Dread
can't read data
File "H5Dio.c", line 592, in H5D__read
can't initialize I/O info
File "H5Dchunk.c", line 1228, in H5D__chunk_io_init
unable to create file chunk selections
File "H5Dchunk.c", line 1721, in H5D__create_chunk_file_map_hyper
can't insert chunk into skip list
File "H5SL.c", line 1122, in H5SL_insert
can't create new skip list node
File "H5Dio.c", line 199, in H5Dread
can't read data
File "H5SL.c", line 791, in H5D__read
can't insert duplicate key

End of HDF5 error back trace

Problems reading the array data.
172.19.128.2 - - [10/Jun/2021 12:59:48] "POST /_dash-update-component HTTP/1.1" 500 -
double free or corruption (out)
Fatal Python error: Aborted

Thread 0x00007f2ee94fb700 (most recent call first):
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socket.py", line 669 in readinto
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 375 in handle_one_request
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/http/server.py", line 427 in handle
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 345 in handle
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 720 in **init**
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 360 in finish_request
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 650 in process_request_thread
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 870 in run
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 932 in _bootstrap_inner
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007f2eeacfe700 (most recent call first):
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/group.py", line 391 in _g_check_has_child
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/group.py", line 708 in _f_get_child
File "/home/niyonx/.local/lib/python3.8/site-packages/tables/group.py", line 836 in **getattr**
File "/project/6003600/niyonx/pytracer/pytracer/gui/core.py", line 92 in get_module
File "/project/6003600/niyonx/pytracer/pytracer/gui/core.py", line 98 in get_function
File "/project/6003600/niyonx/pytracer/pytracer/gui/core.py", line 126 in has_extra_value
File "/project/6003600/niyonx/pytracer/pytracer/gui/core.py", line 133 in get_extra_value
File "/project/6003600/niyonx/pytracer/pytracer/gui/callbacks.py", line 139 in print_heatmap
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1007 in add_context
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1076 in dispatch
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1936 in dispatch_request
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1950 in full_dispatch_request
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 2447 in wsgi_app
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 2464 in **call**
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 312 in execute
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 323 in run_wsgi
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 379 in handle_one_request
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/http/server.py", line 427 in handle
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 345 in handle
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 720 in **init**
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 360 in finish_request
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 650 in process_request_thread
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 870 in run
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 932 in _bootstrap_inner
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f2eeb4ff700 (most recent call first):
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socket.py", line 669 in readinto
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/wsgi.py", line 939 in read
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/wrappers/base_request.py", line 457 in get_data
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 85 in _get_data_for_json
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/wrappers/json.py", line 116 in get_json
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1053 in dispatch
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1936 in dispatch_request
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 1950 in full_dispatch_request
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 2447 in wsgi_app
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 2464 in **call**
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 312 in execute
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 323 in run_wsgi
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 379 in handle_one_request
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/http/server.py", line 427 in handle
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 345 in handle
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 720 in **init**
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 360 in finish_request
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 650 in process_request_thread
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 870 in run
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 932 in _bootstrap_inner
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f2f1e147740 (most recent call first):
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/selectors.py", line 415 in select
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/socketserver.py", line 232 in serve_forever
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 777 in serve_forever
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1009 in inner
File "/home/niyonx/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1052 in run_simple
File "/home/niyonx/.local/lib/python3.8/site-packages/flask/app.py", line 990 in run
File "/home/niyonx/.local/lib/python3.8/site-packages/dash/dash.py", line 1716 in run_server
File "/project/6003600/niyonx/pytracer/pytracer/gui/index.py", line 48 in main
File "/project/6003600/niyonx/pytracer/pytracer/**main**.py", line 33 in pytracer_module_main
File "/project/6003600/niyonx/pytracer/pytracer/**main**.py", line 53 in main
File "/project/6003600/niyonx/pytracer/pytracer/**main**.py", line 59 in <module>
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/runpy.py", line 86 in _run_code
File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/runpy.py", line 193 in _run_module_as_main
Aborted
```

**Comment by yohanchatelain** [comment]
> File "H5Dio.c", line 199, in H5Dread
> can't read data
> File "H5Dio.c", line 592, in H5D__read
> can't initialize I/O info
> File "H5Dchunk.c", line 1228, in H5D__chunk_io_init
> unable to create file chunk selections
> File "H5Dchunk.c", line 1721, in H5D__create_chunk_file_map_hyper
> can't insert chunk into skip list
> File "H5SL.c", line 1122, in H5SL_insert
> can't create new skip list node
> File "H5Dio.c", line 199, in H5Dread
> can't read data
> File "H5SL.c", line 791, in H5D__read
> can't insert duplicate key
> 
> End of HDF5 error back trace
> 
> Problems reading the array data.
> 172.19.128.2 - - [10/Jun/2021 12:59:48] "POST /_dash-update-component HTTP/1.1" 500 -
> double free or corruption (out)
> Fatal Python error: Aborted

Thanks for pointing out the error. Indeed, it is a race condition on HDF5 reading as the backtrace shown.

**Comment by yohanchatelain** [comment]
Resolved in Pytracer 2.0: schema-versioned JSONL and Parquet replace legacy pickle serialization.
